name: manage-azure-policy-eaf7b91f
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Ensure_only_allowed_container_images_in_Kubernetes_cluster_febd0533-8e55-448f-b837-bd0e06f16469/**'
#      - .github/workflows/manage-azure-policy-eaf7b91f.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_eaf7b91f}}
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Ensure_only_allowed_container_images_in_Kubernetes_cluster_febd0533-8e55-448f-b837-bd0e06f16469/**
